### ISSUE TITLE
Unable to transfer files > 2GB using SCP on Windows

### ISSUE THREAD

**Issue by rivy** [bagder/curl#329]
When transferring files greater than 2GB on a Windows machine, curl only downloads the first 2GB of the file. The curl process then halts and returns normally, without an error.

During the transfer, within the progress text, the download file size is shown as 2047MB no matter what the actual file size (if over 2GB). Notably, using FTP to transfer the same file, with the same curl executable and same hosts, shows the correct size in the progress text and fully downloads the entire file. Additionally, transferring the same file using SCP on a linux machine downloads fully and completes correctly.

This occurs with multiple versions of curl and Windows. Most recently:
curl 7.39.0 (x86_64-pc-win32) libcurl/7.39.0 OpenSSL/1.0.1g zlib/1.2.8 WinIDN libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI SPNEGO NTLM SSL libz
Windows 7 and Windows 8.1 Pro

**Comment by jay** [comment]
> curl 7.39.0 (x86_64-pc-win32) libcurl/7.39.0 OpenSSL/1.0.1g zlib/1.2.8 WinIDN libssh2/1.4.3

That release of libssh2 is 2+ years old and this year there is a release. (@gknauf fyi for when you distribute a later release of curl.) It's possible what you are seeing has been fixed in the last 2 years. I'd try a later version of libssh2. While you're at it I'd also try a later version of curl, the current release is 7.43.0 and a later OpenSSL as well.

**Comment by rivy** [comment]
Thanks for the reply.

The problem persists with the most recently available version of curl/OpenSSH:

curl 7.43.0 (x86_64-pc-win32) libcurl/7.43.0 OpenSSL/1.0.2c zlib/1.2.8 WinIDN libssh2/1.4.3_DEV
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smtp smtps
telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz

**Comment by jay** [comment]
Fair enough. Please give me the exact byte size of a file that you've actually seen the problem with and I will create a file that large and try to reproduce with the latest curl, libssh2 and OpenSSL.

**Comment by rivy** [comment]
I have multiple examples, but here are a couple of them:

File 1: size = 3,419,559,900 bytes ... seen as 2047MB .. FAILS
File 2: size = 4,097,085,905 bytes ... seen as 2047MB .. FAILS
File 3: size = 1,998,123,628 bytes ... seen as 1905MB .. Succeeds

Anything over 2GB fails. But, I'm not sure of the exact transition point, in bytes, between a failed and a successful transfer.

Thanks for looking at the problem.

**Comment by bagder** [comment]
This turns out because libssh2 isn't adapted to work with >2GB SCP files. See https://github.com/libssh2/libssh2/blob/master/src/libssh2_priv.h#L794 and https://github.com/libssh2/libssh2/blob/master/src/scp.c#L690

So, unfortunately a bug in libssh2, not in curl.

**Comment by bagder** [comment]
This bug is now https://github.com/libssh2/libssh2/issues/30

**Comment by bagder** [comment]
It'd be lovely if you could head over and try the patch in https://github.com/libssh2/libssh2/pull/31 and work with us to polish that!

**Comment by rivy** [comment]
I'd be happy to help test it on my configurations of you have a Windows binary source, or relatively quick & easy instructions on pulling in all the disparate parts and compiling it.

**Comment by dbyron0** [comment]
https://github.com/dbyron0/libssh2/tree/large_file_windows in combination with https://github.com/dbyron0/curl/tree/large_file_windows has all my changes.  I'd be much obliged if you could exercise it on your setup.  I don't have exact steps for you since I haven't built on windows yet.  The general idea is:

- clone my libssh2 repo
- checkout the large_file_windows branch
- build libssh2
- install libssh2
- clone my curl repo
- checkout the large_file_windows branch
- configure curl to use libssh2 from the directory where you installed it
- build curl
- install curl
- test

**Comment by dbyron0** [comment]
See https://github.com/bagder/curl/pull/451 for current progress.

**Comment by keith-daigle** [comment]
I may be able to find time to pull and build it from scratch on a win32 setup some time later this week.  If rivy or someone else beats me to it please comment here so I don't duplicate your effort.
